### PR TITLE
Repeated sections in code merged, internationalization capabilities added

### PR DESCRIPTION
**Pull request by it-praktyk**
- code rewrote to avoid repeat code sections
- added possibility to translate strings to other languages (internationalization of code)
- Polish translation added

### CODE REVIEW

**Comment by it-praktyk** [comment]
Please wait with accepting the pull request, I'll correct Polish translations and I'll try resolve merge conflicts.

**Comment by it-praktyk** [comment]
@equelin , maybe I'm too tired to find how I can correct my code more.

Please try merge. Thank you.

**Comment by it-praktyk** [comment]
I corrected all conflicts between your and mine forks, and between branches in my forks.

**Comment by equelin** [comment]
Well done @it-praktyk , many many thanks for your work!

**Pull request merged**
