### PR TITLE
feature request

### PR DESCRIPTION
**Pull request by timc4**
propose adding support for inconclusive tests

### CODE REVIEW

**Comment by it-praktyk** [comment]
As an extension of that pull request please open the issue with detailed description of the requested feature.

The best if you can 
- create the set of fake/demo tests - please see the tests included in the demo subfloder as an example
- attach the file with results of tests what contain inconclusive tests - saved as output from  Export-Clixml

**Comment by it-praktyk** [comment]
@equelin , was it any particular reason to don't include inconclusive tests results in Format-Pester output?

**Comment by equelin** [comment]
Maybe because I was lazy at that time ;-)

To be more serious, I was not aware of this feature at that time. It definitly as to be included in Format-Pester.

**Comment by it-praktyk** [comment]
Thx, I'll consider implement it.

**Comment by it-praktyk** [comment]
I work currently to implement it - please check the https://github.com/it-praktyk/Format-Pester/tree/devel at the end of next week (?).
@timc4 your pull request doesn't add nothing to the code so I'm closing it now

**Comment by it-praktyk** [comment]
@timc4 
You can find support for Inconclusive tests in my development branch
https://github.com/it-praktyk/Format-Pester/tree/eb8430d598c1837f9fad0a9f171655976649052b

**Comment by it-praktyk** [comment]
@timc4 
The new iteration of Format-Pester with support for inconclusive tests are ready and can be tested.
https://github.com/it-praktyk/Format-Pester/tree/eed434710295d1ac51078626b38b8d48731732b3

Would you like to test?

**Comment by timc4** [comment]
I will be out of the office from Thursday afternoon 6/1/2017 until Monday morning 6/5/2017  

If you need assistance during that time frame, please email surf@c4.net during business hours and you will be directed to the person best suited to help you.  

Thanks,  

Tim

**Comment by timc4** [comment]
@it-praktyk 
Thanks!  I have just tested and I'm noticing that inconclusive tests do not show up in the resulting pester .html,.txt or .docx files by default.  I see a command line option to only show inconclusive tests, but I don't see an option to include inconclusive tests in the default report.  Is that intentional?

**Comment by it-praktyk** [comment]
@timc4
Does your Pester tests result contain inconclusive too? Empty sections are skipped.

For test you can you fake functions and tests from the demo folder what you can find in Format-Pester repository.
format-pester-1 5-20170607


.

**Comment by it-praktyk** [comment]
@timc4,
any feedback so far?

I changed approach to inluding/skipping sections. The parameters: SkippedOnly, PendingOnly, InconclusiveOnly, introduced recently, were removed and will not be merged to master. The parameters: PassedOnly, FailedOnly left but will be marked as deprecated. I added the parameters: Include, Exclude instead.

The current status you can find here
https://github.com/it-praktyk/Format-Pester/tree/423f5ff64b0f9c5eeb82cb0255d375ee55ccbd08

Please test. Thank you.

**Comment by it-praktyk** [comment]
@timc4 ,
IMHO the current version of Format-Pester https://github.com/it-praktyk/format-pester/tree/devel will be the final version of 1.5.0.

The another one change for including/skipping I introduced - means the parameter 'Exclude' was removed.

Please test. Thank you.

**Comment by timc4** [comment]
First test looks good.  I should have a few “real world” tests done by the end of the week.

 

Thanks!

**Pull request closed without merging**
